{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[31m\u001b[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\u001b[0m\n",
      " * Running on http://127.0.0.1:8050\n",
      "\u001b[33mPress CTRL+C to quit\u001b[0m\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:25] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:25] \"GET /_dash-component-suites/dash/dcc/dash_core_components.v2_9_2m1739804920.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:25] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:25] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:26] \"GET /_dash-component-suites/dash/dash_table/async-table.js HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:26] \"\u001b[36mGET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1\u001b[0m\" 304 -\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:26] \"\u001b[36mGET /_dash-component-suites/dash/dash_table/async-highlight.js HTTP/1.1\u001b[0m\" 304 -\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:26] \"GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1\" 200 -\n",
      "[2025-06-27 10:22:26,391] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:22:26,396] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:26] \"GET /elecciones/static/notificacion.mp3 HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:26] \"GET /_favicon.ico?v=2.9.3 HTTP/1.1\" 200 -\n",
      "[2025-06-27 10:22:26,627] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:22:33,741] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:22:33] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:23:26,393] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:23:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:23:26,403] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:23:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:24:26,390] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:24:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:24:26,395] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:24:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:25:26,406] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:25:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:25:26,411] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:25:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:26:26,399] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:26:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:26:26,400] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:26:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:27:26,418] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:27:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:27:26,419] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:27:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:28:26,401] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:28:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:28:26,402] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:28:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:29:26,400] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:29:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:29:26,403] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:29:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:30:26,405] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:30:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:30:26,409] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:30:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:31:26,402] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:31:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:31:26,403] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:31:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:32:26,406] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:32:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:32:26,408] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:32:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:33:26,391] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:33:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:33:26,393] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:33:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:34:26,399] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:34:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:34:26,400] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:34:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:35:26,396] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:35:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:35:26,402] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:35:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:36:26,399] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:36:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:36:26,402] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:36:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:37:26,401] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:37:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:37:26,405] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:37:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:38:26,400] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:38:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:38:26,402] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:38:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:39:19,080] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:39:19] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:39:26,385] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:39:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:39:26,388] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:39:26] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:40:28,101] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:40:28] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:40:28,102] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:40:28] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:41:28,104] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:41:28] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:41:28,107] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:41:28] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:42:31,098] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:42:31] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:42:31,099] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:42:31] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:43:34,101] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:43:34] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:43:34,104] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:43:34] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:44:37,098] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:44:37] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:44:37,099] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:44:37] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:45:40,103] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:45:40] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:45:40,104] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:45:40] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:46:43,110] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:46:43] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:46:43,112] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:46:43] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:47:46,107] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:47:46] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:47:46,112] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:47:46] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:48:49,111] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:48:49] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:48:49,113] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:48:49] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:49:52,107] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:49:52] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:49:52,111] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:49:52] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:50:55,106] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:50:55] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:50:55,110] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:50:55] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:51:58,102] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:51:58] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:51:58,103] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:51:58] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:53:01,112] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:53:01] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:53:01,114] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:53:01] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:54:04,108] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:54:04] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:54:04,110] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:54:04] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:55:07,118] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:55:07] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:55:07,120] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:55:07] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:56:10,109] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:56:10] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:56:10,112] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:56:10] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:57:13,108] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:57:13] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:57:13,110] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:57:13] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:58:16,100] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:58:16] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:58:16,102] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:58:16] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:59:19,116] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:59:19] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 10:59:19,118] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 10:59:19] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 11:00:21,101] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 11:00:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 11:00:21,103] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 11:00:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 11:01:21,116] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 11:01:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 11:01:21,122] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 11:01:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 11:02:21,109] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: mostrar_alerta() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 11:02:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n",
      "[2025-06-27 11:02:21,111] ERROR in app: Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 2190, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1486, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1484, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/flask/app.py\", line 1469, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/dash/dash.py\", line 1283, in dispatch\n",
      "    ctx.run(\n",
      "  File \"/home/esteban/.local/share/virtualenvs/elecciones2023-mvfi60CS/lib/python3.8/site-packages/django_plotly_dash/_callback.py\", line 82, in add_context\n",
      "    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%\n",
      "TypeError: actualizar_tabla() got an unexpected keyword argument 'long_callback_manager'\n",
      "127.0.0.1 - - [27/Jun/2025 11:02:21] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from django_plotly_dash import DjangoDash\n",
    "from sqlalchemy import create_engine\n",
    "from dash import dcc, dash_table, html, Dash\n",
    "from dash.dependencies import Input, Output, State\n",
    "import dash_bootstrap_components as dbc\n",
    "import plotly.express as px\n",
    "import geopandas\n",
    "import shapely\n",
    "import textwrap\n",
    "import os\n",
    "from dotenv import load_dotenv\n",
    "from functools import lru_cache\n",
    "\n",
    "# Cargar variables de entorno\n",
    "load_dotenv()\n",
    "HOST = os.getenv('DB_HOST', 'localhost')\n",
    "NAME = os.getenv('DB_NAME', 'elecciones23')\n",
    "PASS = os.getenv('DB_PASS', '4rcg1s2024')\n",
    "MAPBOX_TOKEN = os.getenv('MAPBOX_TOKEN', 'pk.eyJ1IjoiemFsaXRvYXIiLCJhIjoiYVJFNTlfbyJ9.mPX8qTsRUGOOETl0CtA-Pg')\n",
    "\n",
    "# Conexión a la base de datos con manejo de errores\n",
    "try:\n",
    "    conn = create_engine(f\"postgresql+psycopg2://elecciones23:{PASS}@{HOST}:5432/{NAME}\")\n",
    "except Exception as e:\n",
    "    print(f\"Error conectando a la base de datos: {e}\")\n",
    "    raise\n",
    "\n",
    "# Consultas SQL\n",
    "sql_base = \"\"\"\n",
    "SELECT tipo, nivel, nivel1, fecha, detalle, subsanada, medidas_adoptadas, distrito, ubicacion as geom\n",
    "FROM novedades_local {where} ORDER BY fecha ASC\n",
    "\"\"\"\n",
    "sql_generales_base = \"\"\"\n",
    "SELECT tipo, \n",
    "       nivel AS nivel1,\n",
    "       CASE\n",
    "           WHEN nivel::text = '1'::text THEN 'Media'::text\n",
    "           WHEN nivel::text = '2'::text THEN 'Alta'::text\n",
    "           WHEN nivel::text = '3'::text THEN 'Crítica'::text\n",
    "           ELSE NULL::text\n",
    "       END AS nivel,\n",
    "       to_char(fecha, 'dd/mm/YYYY HH:MI'::text) AS fecha, detalle, subsanada, medidas_adoptadas, distrito,\n",
    "       ubicacion as geom\n",
    "FROM novedades_generales {where} ORDER BY fecha ASC\n",
    "\"\"\"\n",
    "sql_distritos = \"SELECT nam as distrito FROM distritos\"\n",
    "sql_malvinas = \"\"\"\n",
    "SELECT nam, geom, -51.74153477642776 as lat, 59.38576589695881 as lon FROM public.malvinas\n",
    "\"\"\"\n",
    "\n",
    "# Función para consultas dinámicas con caché\n",
    "@lru_cache(maxsize=32)\n",
    "def cached_read_postgis(sql, conn_str, params_tuple=()):\n",
    "    params = dict(params_tuple)\n",
    "    return geopandas.read_postgis(sql, conn, params=params).to_crs(4326)\n",
    "\n",
    "def get_data(distrito=None, subsanada=None):\n",
    "    where_clauses = []\n",
    "    params = {}\n",
    "    if distrito and distrito != 'TODOS':\n",
    "        where_clauses.append(\"distrito = %(distrito)s\")\n",
    "        params['distrito'] = distrito\n",
    "    if subsanada:\n",
    "        where_clauses.append(\"subsanada = %(subsanada)s\")\n",
    "        params['subsanada'] = subsanada\n",
    "    where = \"WHERE \" + \" AND \".join(where_clauses) if where_clauses else \"\"\n",
    "    sql = sql_base.format(where=where)\n",
    "    return cached_read_postgis(sql, str(conn), tuple(params.items()))\n",
    "\n",
    "def get_data_generales(distrito=None, subsanada=None):\n",
    "    where_clauses = []\n",
    "    params = {}\n",
    "    if distrito and distrito != 'TODOS':\n",
    "        where_clauses.append(\"distrito = %(distrito)s\")\n",
    "        params['distrito'] = distrito\n",
    "    if subsanada:\n",
    "        where_clauses.append(\"subsanada = %(subsanada)s\")\n",
    "        params['subsanada'] = subsanada\n",
    "    where = \"WHERE \" + \" AND \".join(where_clauses) if where_clauses else \"\"\n",
    "    sql = sql_generales_base.format(where=where)\n",
    "    return cached_read_postgis(sql, str(conn), tuple(params.items()))\n",
    "\n",
    "# Cargar datos iniciales\n",
    "df = get_data()\n",
    "df_generales = get_data_generales()\n",
    "distritos_df = pd.read_sql(sql_distritos, conn)\n",
    "gdf_poligono = geopandas.read_postgis(sql_malvinas, conn, geom_col='geom').to_crs(epsg=4326)\n",
    "poligono_geojson = gdf_poligono.__geo_interface__\n",
    "\n",
    "# Agregar coordenadas\n",
    "df['lon'] = df['geom'].x\n",
    "df['lat'] = df['geom'].y\n",
    "df_generales['lon'] = df_generales['geom'].x\n",
    "df_generales['lat'] = df_generales['geom'].y\n",
    "\n",
    "def generar_tabla(df1, id):\n",
    "    if df1.empty:\n",
    "        return html.Div(\"No hay datos para mostrar\")\n",
    "    df1 = df1.drop(columns=['geom'], errors='ignore')\n",
    "    return dash_table.DataTable(\n",
    "        data=df1.to_dict('records'),\n",
    "        columns=[{\"name\": i, \"id\": i.lower()} for i in ['Fecha', 'Tipo', 'Detalle']],\n",
    "        id=id,\n",
    "        editable=False,\n",
    "        filter_action=\"native\",\n",
    "        sort_action=\"native\",\n",
    "        sort_mode=\"multi\",\n",
    "        selected_columns=[],\n",
    "        selected_rows=[],\n",
    "        style_table={'overflowX': 'scroll'},\n",
    "        style_cell={\n",
    "            'fontSize': 11, 'font-family': 'sans-serif', 'textAlign': 'center',\n",
    "            'whiteSpace': 'normal', 'overflow': 'hidden', 'textOverflow': 'ellipsis'\n",
    "        },\n",
    "        page_action=\"native\",\n",
    "        page_current=0,\n",
    "        page_size=8,\n",
    "        style_data={'color': 'black', 'backgroundColor': 'white'},\n",
    "        style_data_conditional=[\n",
    "            {\"if\": {\"statePts\": \"active\"}, \"backgroundColor\": \"rgb(102, 102, 102)\", \"border\": \"3px solid white\", \"color\": \"white\"},\n",
    "            {\"if\": {\"state\": \"selected\"}, \"backgroundColor\": \"rgba(0, 116, 217, 0.3)\"}\n",
    "        ],\n",
    "        style_header={'backgroundColor': 'rgb(210, 210, 210)', 'color': 'black', 'fontWeight': 'bold'}\n",
    "    )\n",
    "\n",
    "def crear_mapa(df, zoom, lat_cen=None, lon_cen=None):\n",
    "    px.set_mapbox_access_token(MAPBOX_TOKEN)\n",
    "    punto = shapely.Point(-59.5236, -51.7963)\n",
    "    gdf_circulo = geopandas.GeoDataFrame(geometry=[punto], crs=\"EPSG:4326\")\n",
    "    gdf_circulo = gdf_circulo.to_crs(\"EPSG:32721\")\n",
    "    gdf_circulo['geometry'] = gdf_circulo.geometry.buffer(280000)\n",
    "    gdf_circulo = gdf_circulo.to_crs(\"EPSG:4326\")\n",
    "    \n",
    "    center = dict(lat=lat_cen, lon=lon_cen) if lat_cen and lon_cen else dict(lat=df['lat'].mean() if not df.empty else -34.603722, lon=df['lon'].mean() if not df.empty else -58.381592)\n",
    "    \n",
    "    df['detalle2'] = ['<br>'.join(textwrap.wrap(x, width=50)) for x in df['detalle']]\n",
    "    df['medidas2'] = ['<br>'.join(textwrap.wrap(x, width=50)) for x in df['medidas_adoptadas']]\n",
    "    \n",
    "    color_map = {\"Media\": \"#b5c717\", \"Alta\": \"#FF9900\", \"Crítica\": \"#FF1E00\"}\n",
    "    \n",
    "    mapa = px.scatter_mapbox(\n",
    "        data_frame=df, lat=\"lat\", lon=\"lon\",\n",
    "        hover_name=\"nivel\", color='nivel',\n",
    "        category_orders={'nivel': ['Media', 'Alta', 'Crítica']},\n",
    "        color_discrete_map=color_map,\n",
    "        hover_data=dict(\n",
    "            distrito=True, tipo=True, fecha=True, detalle2=True,\n",
    "            subsanada=True, medidas2=True, lat=False, lon=False\n",
    "        ),\n",
    "        zoom=zoom, height=800, center=center\n",
    "    )\n",
    "    \n",
    "    mapa.update_traces(\n",
    "        marker={'size': 13},\n",
    "        hovertemplate=\"<br>\".join([\n",
    "            \"<b>Nombre:</b> %{customdata[2]}\",\n",
    "            \"<b>Distrito:</b> %{customdata[0]}\",\n",
    "            \"<b>Tipo:</b> %{customdata[1]}\",\n",
    "            \"<b>Fecha:</b> %{customdata[2]}\",\n",
    "            \"<b>Detalle:</b> %{customdata[3]}\",\n",
    "            \"<b>Subsanada:</b> %{customdata[4]}\",\n",
    "            \"<b>Medidas Adoptadas:</b> %{customdata[5]}\"\n",
    "        ])\n",
    "    )\n",
    "    \n",
    "    mapa.update_layout(\n",
    "        hoverlabel_bgcolor=\"#FFFFFF\", coloraxis_showscale=False,\n",
    "        mapbox_style=\"open-street-map\", margin={\"r\": 0, \"t\": 0, \"l\": 0, \"b\": 0}\n",
    "    )\n",
    "    \n",
    "    mapa.add_choroplethmapbox(\n",
    "        geojson=gdf_circulo.__geo_interface__,\n",
    "        locations=gdf_circulo.index,\n",
    "        z=[1] * len(gdf_circulo),\n",
    "        colorscale=[[0, 'rgba(170, 211, 223, 1)'], [1, 'rgba(170, 211, 223, 1)']],\n",
    "        showscale=False, hoverinfo='text', text=['Islas Malvinas'] * len(gdf_poligono),\n",
    "        marker_line_color='rgba(170, 211, 223, 0.6)', marker_line_width=1\n",
    "    )\n",
    "    \n",
    "    mapa.add_choroplethmapbox(\n",
    "        geojson=poligono_geojson,\n",
    "        locations=gdf_poligono.index,\n",
    "        z=[1] * len(gdf_poligono),\n",
    "        colorscale=[[0, 'rgb(242, 239, 233, 0.6)'], [1, 'rgb(242, 239, 233, 0.6)']],\n",
    "        showscale=False, hoverinfo='text', text=['Islas Malvinas'] * len(gdf_poligono)\n",
    "    )\n",
    "    \n",
    "    return mapa\n",
    "\n",
    "def graf_nov_loc(df):\n",
    "    estado_counts = df['nivel'].value_counts()\n",
    "    df_pie = pd.DataFrame({'Nivel': estado_counts.index, 'Cantidad': estado_counts.values})\n",
    "    color_map = {\"Media\": \"#b5c717\", \"Alta\": \"#FF9900\", \"Crítica\": \"#FF1E00\"}\n",
    "    \n",
    "    fig = px.pie(\n",
    "        df_pie, values='Cantidad', names='Nivel', title='Novedades en locales',\n",
    "        hole=.4\n",
    "    )\n",
    "    \n",
    "    fig.update_traces(\n",
    "        textposition='inside', textinfo='percent+label',\n",
    "        marker=dict(colors=[color_map.get(x, '#000000') for x in df_pie['Nivel']])\n",
    "    )\n",
    "    \n",
    "    fig.update_layout( plot_bgcolor='rgb(40, 40, 40)', title_x=0.5,autosize=True, height=400,\n",
    "                               paper_bgcolor='rgb(40, 40, 40)', title_font_size=25, font_color='rgb(255, 255, 255)',showlegend=True,font_size=10\n",
    "                               ,legend=dict(orientation=\"h\", ))\n",
    "    \n",
    "    return fig\n",
    "\n",
    "app2 = Dash(external_stylesheets=[dbc.themes.DARKLY])\n",
    "\n",
    "app2.layout = html.Div([\n",
    "    dcc.Store(id='row-count', data={'count': len(df)}),\n",
    "    dbc.Alert(\"Hay Novedades Nuevas!!\", id=\"alerta\", is_open=False, color=\"danger\", duration=4000),\n",
    "    html.Audio(id='audio', autoPlay=False, src='/elecciones/static/notificacion.mp3'),\n",
    "    dbc.Row([html.H2('NOVEDADES', style={'textAlign': 'center', 'background-color': '#267300'})], className=\"g-0\"),\n",
    "    dbc.Row([\n",
    "        dbc.Col([\n",
    "            dbc.Select(\n",
    "                id=\"selec_distrito\",\n",
    "                options=[{\"label\": 'TODOS', \"value\": 'TODOS'}] +\n",
    "                        [{\"label\": x, \"value\": x} for x in distritos_df['distrito'].drop_duplicates().sort_values()],\n",
    "                placeholder='DISTRITO'\n",
    "            )\n",
    "        ]),\n",
    "        dbc.Col([\n",
    "            dbc.Select(\n",
    "                id=\"Subsanada\",\n",
    "                options=[{\"label\": 'No', \"value\": 'No'}, {\"label\": 'Sí', \"value\": 'Sí'}],\n",
    "                placeholder='SUBSANADO'\n",
    "            )\n",
    "        ])\n",
    "    ], className=\"m-2 g-0\"),\n",
    "    dbc.Row([\n",
    "        dbc.Col([\n",
    "            dbc.Row(html.H3('NOVEDADES DE LOCAL', style={'textAlign': 'center', 'background-color': '#267300'})),\n",
    "            dcc.Loading(id=\"ls-loading-3\", children=[generar_tabla(df, 'datatable1')]),\n",
    "            dbc.Row(html.H3('NOVEDADES GENERALES', style={'textAlign': 'center', 'background-color': '#267300'})),\n",
    "            dcc.Loading(id=\"ls-loading-1\", children=[generar_tabla(df_generales, 'datatable2')])\n",
    "        ], md=5),\n",
    "        dbc.Col([\n",
    "            dcc.Loading(id=\"ls-loading-4\", children=[dcc.Graph(id='mapa', figure=crear_mapa(df, 3))])\n",
    "        ], md=4),\n",
    "        dbc.Col([\n",
    "            dcc.Loading(id=\"ls-loading-5\", children=[dcc.Graph(id='pie_3', figure=graf_nov_loc(df))]),\n",
    "            dcc.Loading(id=\"ls-loading-6\", children=[dcc.Graph(id='pie4', figure=graf_nov_loc(df_generales))])\n",
    "        ], md=3)\n",
    "    ], className=\"g-0\"),\n",
    "    dcc.Interval(id='interval-component', interval=60 * 1000, n_intervals=0)\n",
    "])\n",
    "\n",
    "@app2.callback(\n",
    "    [Output('datatable1', 'data'), Output('datatable2', 'data'), Output('mapa', 'figure'),\n",
    "     Output('pie_3', 'figure'), Output('pie4', 'figure')],\n",
    "    [Input('interval-component', 'n_intervals'), Input('selec_distrito', 'value'),\n",
    "     Input('Subsanada', 'value'), Input('datatable1', 'active_cell'),\n",
    "     Input('datatable1', 'derived_virtual_data')],\n",
    "    [State('datatable1', 'data')]\n",
    ")\n",
    "def actualizar_tabla(n_intervals, distrito, subsanada, active_cell, nueva_tabla, tabla):\n",
    "    try:\n",
    "        df = get_data(distrito, subsanada)\n",
    "        df_generales = get_data_generales(distrito, subsanada)\n",
    "        df1 = df.drop(columns=['geom'], errors='ignore')\n",
    "        df1_generales = df_generales.drop(columns=['geom'], errors='ignore')\n",
    "        \n",
    "        zoom = 3\n",
    "        lat_cen, lon_cen = None, None\n",
    "        if active_cell and nueva_tabla:\n",
    "            tabla = nueva_tabla\n",
    "            lat_cen = tabla[active_cell['row']]['lat']\n",
    "            lon_cen = tabla[active_cell['row']]['lon']\n",
    "            zoom = 18\n",
    "        \n",
    "        return (\n",
    "            df1.to_dict('records'),\n",
    "            df1_generales.to_dict('records'),\n",
    "            crear_mapa(df, zoom, lat_cen, lon_cen),\n",
    "            graf_nov_loc(df),\n",
    "            graf_nov_loc(df_generales)\n",
    "        )\n",
    "    except Exception as e:\n",
    "        print(f\"Error en callback: {e}\")\n",
    "        return [], [], {}, {}, {}\n",
    "\n",
    "@app2.callback(\n",
    "    [Output('alerta', 'is_open'), Output('audio', 'autoPlay'), Output('row-count', 'data')],\n",
    "    [Input('interval-component', 'n_intervals')],\n",
    "    [State('row-count',  'data')]\n",
    ")\n",
    "def mostrar_alerta(n_intervals, row_count):\n",
    "    try:\n",
    "        df = get_data()\n",
    "        new_count = len(df)\n",
    "        count_data = row_count.get('count', 0)\n",
    "        if count_data != new_count:\n",
    "            return True, True, {'count': new_count}\n",
    "        return False, False, {'count': new_count}\n",
    "    except Exception as e:\n",
    "        print(f\"Error en alerta: {e}\")\n",
    "        return False, False, row_count\n",
    "\n",
    "app2.run_server()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "elecciones2023-mvfi60CS",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
